-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 18:51:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Абитуриент
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Абитуриент
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Абитуриент` DEFAULT CHARACTER SET utf8 ;
USE `Абитуриент` ;

-- -----------------------------------------------------
-- Table `Абитуриент`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Абитуриент`.`department` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `name_department` VARCHAR(30) NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Абитуриент`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Абитуриент`.`subject` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `name_subject` VARCHAR(30) NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Абитуриент`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Абитуриент`.`program` (
  `program_id` INT NOT NULL AUTO_INCREMENT,
  `name_program` VARCHAR(50) NULL,
  `department_id` INT NULL,
  `plan` INT NULL,
  PRIMARY KEY (`program_id`),
  INDEX `department_id_idx` (`department_id` ASC) VISIBLE,
      FOREIGN KEY (`department_id`)
    REFERENCES `Абитуриент`.`department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Абитуриент`.`enrollee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Абитуриент`.`enrollee` (
  `enrollee_id` INT NOT NULL AUTO_INCREMENT,
  `name_enrollee` VARCHAR(50) NULL,
  PRIMARY KEY (`enrollee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Абитуриент`.`achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Абитуриент`.`achievement` (
  `achievement_id` INT NOT NULL AUTO_INCREMENT,
  `name_achievement` VARCHAR(30) NULL,
  `bonus` INT NULL,
  PRIMARY KEY (`achievement_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Абитуриент`.`enrollee_achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Абитуриент`.`enrollee_achievement` (
  `enrollee_achiev_id` INT NOT NULL AUTO_INCREMENT,
  `enrollee_id` INT NULL,
  `achievement_id` INT NULL,
  PRIMARY KEY (`enrollee_achiev_id`),
  INDEX `enrollee_id_idx` (`enrollee_id` ASC) VISIBLE,
  INDEX `achievement_id_idx` (`achievement_id` ASC) VISIBLE,
      FOREIGN KEY (`enrollee_id`)
    REFERENCES `Абитуриент`.`enrollee` (`enrollee_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
      FOREIGN KEY (`achievement_id`)
    REFERENCES `Абитуриент`.`achievement` (`achievement_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Абитуриент`.`program_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Абитуриент`.`program_subject` (
  `program_subject_id` INT NOT NULL AUTO_INCREMENT,
  `program_id` INT NULL,
  `subject_id` INT NULL,
  `min_result` INT NULL,
  PRIMARY KEY (`program_subject_id`),
  INDEX `program_id_idx` (`program_id` ASC) VISIBLE,
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
      FOREIGN KEY (`program_id`)
    REFERENCES `Абитуриент`.`program` (`program_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
      FOREIGN KEY (`subject_id`)
    REFERENCES `Абитуриент`.`subject` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Абитуриент`.`program_enrollee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Абитуриент`.`program_enrollee` (
  `program_enrollee_id` INT NOT NULL AUTO_INCREMENT,
  `program_id` INT NULL,
  `enrollee_id` INT NULL,
  PRIMARY KEY (`program_enrollee_id`),
  INDEX `program_id_idx` (`program_id` ASC) VISIBLE,
  INDEX `enrollee_id_idx` (`enrollee_id` ASC) VISIBLE,
      FOREIGN KEY (`program_id`)
    REFERENCES `Абитуриент`.`program` (`program_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
      FOREIGN KEY (`enrollee_id`)
    REFERENCES `Абитуриент`.`enrollee` (`enrollee_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Абитуриент`.`enrollee_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Абитуриент`.`enrollee_subject` (
  `enrollee_subject_id` INT NOT NULL AUTO_INCREMENT,
  `enrollee_id` INT NULL,
  `subject_id` INT NULL,
  `result` INT NULL,
  PRIMARY KEY (`enrollee_subject_id`),
  INDEX `enrollee_id_idx` (`enrollee_id` ASC) VISIBLE,
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
      FOREIGN KEY (`enrollee_id`)
    REFERENCES `Абитуриент`.`enrollee` (`enrollee_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
      FOREIGN KEY (`subject_id`)
    REFERENCES `Абитуриент`.`subject` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
